language: php
php:
  - 5.5
  - 5.4
  - hhvm
before_install:
  - git clone --recursive https://www.github.com/in-toto/in-toto.git
  - pwd
  - ls -a
  - cd in-toto 
install:
  - pwd
  - ls -a
  - sudo -H pip install -e . 
  - export SIMPLE_SETTINGS=toto.settings
  - git clone --recursive https://www.github.com/b0n0n/test_proj1
  - ls -a
  - ls toto
  - ./toto/toto-run.py --step-name funktest --products ./test_proj1/test --key ./test_proj1/bob – echo
  - cd ..
script: phpunit Test.php
